name: CI - Clinica API

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar aplicación
        run: dotnet build --no-restore --configuration Release

      - name: Ejecutar pruebas
        run: dotnet test --no-build --configuration Release --verbosity normal
        
